### ISSUE TITLE
Could you point me to where you calculate the ranking order for repos?

### ISSUE THREAD

**Issue by tyler17** [k0kubun/githubranking#3]

**Comment by k0kubun** [comment]
The repository data was imported by [this batch](https://github.com/k0kubun/githubranking/tree/091252cc3a9344c524f95920ebb91ace895d517e/batches). Because fetching all starts via GitHub API v3 was very hard, I managed to import them with many concurrent requests using goroutine. While I tried to rewrite it several times, I couldn't achieve it. It requires many requests but I don't want to attack GitHub.

The ranking calculation itself was implemented with [redis](https://github.com/k0kubun/githubranking/blob/304d507b50c3a573bd74cc4d7287a68e5c53a4c7/app/models/concerns/rankable.rb).
